website/auth.py
from flask import Blueprint, render_template, redirect, request, flash, url_for, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required
from .models import User, Task
from . import db
import uuid
import os
from werkzeug.utils import secure_filename

PROFILE_PICS_SUBDIR = "profile_pics"


def checkFile(name: str) -> bool: #This checks the file name to ensure that it is compatible
    allowed = {"png", "gif", "jpg", "jpeg", "avif", "webp"}
    if "." in set(name):
        diff = name.split(".")

        if len(diff) == 2:

            name, ext = diff[0], diff[1]

            if ext.lower() in allowed:

                return True

            return False
        return False
    return False

def checkUserConditions(firstName, lastName, email, password1, password2): #This collects all the user's primary info and checks if it's correct. It then creates a user model if it is.
    
    user = User.query.filter_by(email = email).first()
 
    if user:
        flash("Email already exists", category="error")
        return redirect(url_for("auth.sign_up"))
            
    if len(firstName) < 2:
        flash("First name must be at least 2 characters", category='error')
        return redirect(url_for("auth.sign_up"))

    elif len(lastName) < 2:
        flash("Last name must be at least 2 characters", category='error')
        return redirect(url_for("auth.sign_up"))

    elif ("." not in email) or ("@" not in email) or (len(email) < 2):
        flash("Invalid email", category='error')
        return redirect(url_for("auth.sign_up"))

    elif len(password1) < 7:
        flash("Password must be at least 7 characters", category='error')
        return redirect(url_for("auth.sign_up"))

    elif password1 != password2:
        flash("Passwords must match", category='error')
        return redirect(url_for("auth.sign_up"))

    user = User(email = email, 
                firstName = firstName, 
                lastName=lastName, 
                password = generate_password_hash(password1),
                )
            
    return user

auth = Blueprint("auth", __name__) #Initianlises the auth blueprint



@auth.route("/login", methods = ["POST", "GET"])
def login():
    if request.method == "POST":

        email = request.form["email"].strip()

        password = request.form["password"].strip()

        if not email:
            return redirect("/login")


        if not password:
            return redirect("/login")


        if email and password:

            user = User.query.filter_by(email = email).first()

            if user:

                if check_password_hash(pwhash=user.password, password=password):
                    if login_user(user=user, remember=True):
                        flash("Logged in successfully", category="success")
                        return redirect(f"/user/home")
                    else:
                        flash("Wrong password", category="error")
                        return redirect("/login")

                else:
                    return redirect("/login")
            else:
                flash("User account does not exist. Create an account here", category="error")
                return redirect("/sign_up")


    else:
        return render_template("login.html")




"""Add a feature such that a user doesn't have to type all their information again if one thing goes wrong"""
@auth.route("/sign_up", methods = ["POST", "GET"])
def sign_up():

    if request.method == "POST":

        """
            First check for all the compulsory requirements and if they are all met, create the user instance. 
            Then check all optional user information, if they are given, just adjust the user instance with dot notation.
            Eg, user.optional_info = some_data
        """

        firstName = request.form["firstName_signUp"].strip()

        lastName = request.form["lastName_signUp"].strip()

        email = request.form["email_signUp"].strip()

        password1 = request.form["password1_signUp"].strip()

        password2 = request.form["password2_signUp"].strip()

        profilePic = request.files["profilePic"]

        user = checkUserConditions(firstName, lastName, email, password1, password2)


        if profilePic:
            if not checkFile(profilePic.filename): #If the picture is of an invalid format
                flash("Profile picture is of invalid format", category='error')
                return redirect(url_for("auth.sign_up"))

            """
                Here, we process the file given as the PFP.
                Get the file. 
                Generaate a unique file naem for that file. 
                Save it to the destination folder. 
                Add it to the user model.
            """
            profile_pic_dir = os.path.join(current_app.config["UPLOAD_FOLDER"], PROFILE_PICS_SUBDIR)

            uploaded_user_filename = profilePic.filename
            secure_uploaded_filename = secure_filename(uploaded_user_filename) #This gives a secure format for the file name to avoid any issues.

            name, ext = secure_uploaded_filename.rsplit(".", 1)  #Split the file into the name and its extension

            unique_file_name = f"{uuid.uuid4().hex}.{ext.lower()}" #Generates a unique file name for that file.
            user.uniqueProfilePicName = unique_file_name #Stores the unique file name in the DB for reference.

            unique_file_path = os.path.join(profile_pic_dir, unique_file_name) #Generates a unique file path for that picture with the uique file name. It is the path that the picture will be stored in.

            profilePic.save(unique_file_path) #Stores the image in the destination folder with the full file path(folder name + unique name generated). It means "Save this image at this location on my device"

            user.profilePic = f"uploads/{PROFILE_PICS_SUBDIR}/{unique_file_name}" #Stores the relative file name in the DB. Refrences that particular image with the user.

            
            
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=True)

        flash("Account created successfully", category="success")

        return redirect(f"/user/home")
    else:
        return render_template("sign_up.html")




@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged out successfully", category="success")
    return redirect("/login")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" 
        crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/general_style_sheet.css') }}">

    {% block csStyles %}{% endblock %} <!-- This is what is used to link individual html pages with specific CSS files -->

    {% block title %}{% endblock %}
</head>
<body style="margin: 0.5em;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">

                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/user/home">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/user/profile">Profile</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/logout">Logout</a>
                        </li> 

                        <li class="nav-item">
                            <a class="nav-link active" href="/user/edit_profile">Edit Profile</a>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Login</a>
                        </li>     

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                        </li>   
                    {% endif %}     
                </ul>
    

            </div>

        </div>
        
    </nav><br>

    {% with messages = get_flashed_messages(with_categories=true) %}
    
        {% if messages %}
        
            {% for category, message in messages %}
            
                {% if category=='error' %}

                    <div class="alert alert-danger" role="alert" id="errorAlert">

                        {{ message }} 

                        <button class="close" id="errorClear" type="button" data-dismiss="alert" onclick="errorcls()"><span aria-hidden="true">&times;</span></button>

                    </div>
                
                {% else %}

                    <div class="alert alert-success" role="alert" id="successAlert">

                        {{ message }} 

                        <button class="close" id="successClear" type="button" data-dismiss="alert" onclick="successcls()"><span aria-hidden="true">&times;</span></button>

                    </div>

                {% endif %}
            
            {% endfor %}

        {% endif %}

    {% endwith %}

    {% block form %}{% endblock %}

    {% block body %}{% endblock %}

    {% block rndm %}{% endblock %}


    {% block jsFiles %}{% endblock %} <!-- This is what is used to link individual html pages with specific JS files -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js" integrity="sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename = 'js/general_script.js' ) }}"></script>


</body>
</html>

website/templates/edit_profile.html
{% extends "base.html" %}

{% block csStyles %}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/edit_profile_style.css') }}">

{% endblock %}

{% block form %}

<form action="/user/edit_profile" method="post" enctype="multipart/form-data" id="edit_profile_form">
  
    <h1>Edit profile</h1><br>

    <div class="input-group mb-3">
        <span class="input-group-text">First Name</span>
        <input type="text" class="form-control" value="{{ current_user.firstName }}" placeholder="Edit first name" name="editFirstName">
    </div>



    <div class="input-group mb-3">
        <span class="input-group-text">Last Name</span>
        <input type="text" class="form-control" value="{{ current_user.lastName }}" placeholder="Edit last name" name="editLastName">
    </div>


    <div class="input-group mb-3">
        <span class="input-group-text">Email</span>
        <input type="text" class="form-control" value="{{ current_user.email }}" placeholder="Edit email" name="editEmail">
    </div>


    <div>
        <input type="file" id="editPFP" accept="image/*" class="form-control" name="editPFP">
    </div>

    <br>

    <button type="submit" id="sign_up_btn_submit">Confirm changes</button>

</form>

{% endblock %}

{% block jsFiles %}
    <script src="{{ url_for('static', filename = 'js/control_signup.js' ) }}"></script>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}


{% block body %}

<h1>Welcome: {{ current_user.firstName }}</h1>

<h1>Home Page</h1>




<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, numquam facilis? Dolorum magni nihil consequuntur nisi ducimus? Velit repellat repellendus esse! Quaerat debitis numquam quod mollitia excepturi voluptatem veritatis voluptas?</p>




{% endblock %}

website/templates/login.html
{% extends "base.html" %}


{% block form %}

<h1 style="text-align: center;">Login Page</h1>


<form action="/login" method="post">

    <div class="mb-3">

        <label for="email" class="form-label">Enter Email</label>
        <input type="email" name="email" id="email" placeholder="Email" required class="form-control"> <br>

    </div>


    <div class="mb-3">

        <label for="password" class="form-label">Enter Password</label>
        <input type="password" name="password" id="password" placeholder="Password" required class="form-control"><br>

    </div>

    
    

    <button type="submit">Login</button>

</form><br>

<p>Don't have an account? Sign up <a href="/sign_up">here</a>.</p>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block csStyles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile_style.css') }}">
{% endblock %}

{% block body %}

<div id="profile_container" class="card" style="text-align: center; width: 18rem;">

    
    <img src="{{ url_for('static', filename=current_user.profilePic) }}" alt="Profile Pic" id="profile_pic" class="card-img-top">        

    <div id="profile_info" class="card-body">

        <h3 id="first_name" class="card-title">First name: {{ current_user.firstName }}</h3>
        <h5>Last name: {{ current_user.lastName }}</h5>

        <p>Email: <a href="mailto:{{ current_user.email }}">{{ current_user.email }}</a></p>


    </div>
    

</div>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}


{% block form %}

<h1 style="text-align: center;">Sign Up Page</h1>


<form action="/sign_up" method="post" enctype="multipart/form-data" id="SignUpForm">



    <div class="mb-3">

        <label for="firstName_signUp" class="form-label">Enter First Name</label>
        <input type="text" name="firstName_signUp" id="firstName_signUp" placeholder="First Name" class="form-control">


    </div>



    <div class="mb-3">

        <label for="lastName_signUp" class="form-label">Enter Last Name</label>
        <input type="text" name="lastName_signUp" id="lastName_signUp" placeholder="Last Name" class="form-control">

    </div>


    <div class="mb-3">

        <label for="email_signUp" class="form-label">Enter Email</label>
        <input type="email" name="email_signUp" id="email_signUp" placeholder="Email" class="form-control">


    </div>


    <div class="mb-3">

        <label for="password1_signUp" class="form-label">Enter Password</label>
        <input type="password" name="password1_signUp" id="password1_signUp" placeholder="Password" class="form-control">


    </div>


    <div class="mb-3">

        <label for="password2_signUp" class="form-label">Confirm password</label>
        <input type="password" name="password2_signUp" id="password2_signUp" placeholder="Confirm Password" class="form-control">

    </div>

    

    <div class="mb-3">

        <label for="profilePic" class="form-label">Chose Profile Picture</label>
        <input type="file" name="profilePic" id="profilePic" accept="image/*" class="form-control">

    </div>


    <button type="submit" id="sign_up_btn_submit" disabled>Sign up</button>

</form>

{% endblock %}

{% block jsFiles %}
    <script src="{{ url_for('static', filename = 'js/control_signup.js' ) }}"></script>
{% endblock %}